#!/bin/bash

#revoke user or host certificate
#usage: revoke.sh <user|hostname>

if [ -f /storage/crt/$1.cert ]
then
  if [ "$1" == "$CAHOST" ] || [ "$1" == "ca" ] 
  then
    echo "Never remove CA certificate!"
  else
    openssl ca -config /usr/lib/ssl/CA/ca.req -revoke /storage/crt/$1.cert -passin 'file:/password'
    openssl ca -config /usr/lib/ssl/CA/ca.req -gencrl -out /var/www/ca.crl -passin 'file:/password'
    rm /storage/crt/$1.cert
  fi
else
  echo Searching in issued certificates...
  FOUND=0
  for A in `ls -1 /usr/lib/ssl/CA/newcerts`
  do
    cat $A | grep $1 >/dev/null 2>&1
    if [ $? -eq 0 ]
    then
      openssl ca -config /usr/lib/ssl/CA/ca.req -revoke /usr/lib/ssl/CA/newcerts/$A -passin 'file:/password'
      FOUND=1
    fi
  done
  if [ $FOUND -ne 0 ]
  then
    openssl ca -config /usr/lib/ssl/CA/ca.req -gencrl -out /var/www/ca.crl -passin 'file:/password'
  else
    echo "$1 is not found"
  fi
fi
